### ISSUE TITLE
No Feeds - pystemon

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/pystemon#3]
Hi,
Ive added 2 new screens for pystemon... one for the app and one for the feeder
activated the . ./AILENV/bin/activate in both

ran the python2 ./pystemon.py in one
in the other I ran the feeder script

Both look like their running ok
pystemon is using pastebin seems to identify things to download but no feeds or queues

if I use pastebin_pro after whitelisting the IP i get 
[2019-09-17 10:56:54,712] Retry 75/100 for http://pastebin.com/api_scrape_item.php?i=WkYLDfVT
[2019-09-17 10:56:54,826] Failed to download the page because of other HTTPlib error proxy error http://pastebin.com/api_scrape_item.php?i=WkYLDfVT trying again.

can someone poke me in the right direction?

**Comment by viszsec** [comment]
> Looks like pystemon's requirements are not installed, try:
> 
> ```python
> pip3 install -r requirements.txt
> ```

gally,

I have installed the requirements..but when i try to run with ./pystemon.py or even with python3, this came out..any idea whats going on?

(AILENV) ail@ail:~/ail-framework/pystemon$ python3 ./pystemon.py
  File "./pystemon.py", line 69
    exit('You need python version 2.7 or newer.')
                                                ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by gallypette** [comment]
Oops, pystemon is python2 not 3.
On 20.04 I installed it with

```
virtualenv -p python2 venv
. ./venv/bin/activate
pip install -r requirements.txt
```

But then I run into this issue https://github.com/CIRCL/pystemon/issues/4

**Comment by viszsec** [comment]
> Oops, pystemon is python2 not 3.
> On 20.04 I installed it with
> 
> ```
> virtualenv -p python2 venv
> . ./venv/bin/activate
> pip install -r requirements.txt
> ```
> 
> But then I run into this issue #4

Followed the same as you did and got this error with python2.

(venv) ail@ail:~/ail-framework/pystemon$ python2 ./pystemon.py
./pystemon.py:868: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yamlconfig = yaml.load(open(configfile))
Site: safebin.net is disabled.
Site: slexy.org is enabled, adding to pool...
Site: pastebin.com is enabled, adding to pool...
Site: gist.github.com is disabled.
Site: pastebin.com_pro is disabled.
Site: codepad.org is disabled.
[2021-01-04 03:14:21,126] Using default IP address
[2021-01-04 03:14:21,127] Using default IP address
[2021-01-04 03:14:21,128] Downloading list of new pastes from slexy.org. Will check again in 22 seconds
[2021-01-04 03:14:21,128] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2021-01-04 03:14:21,129] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2021-01-04 03:14:21,130] Downloading list of new pastes from pastebin.com. Will check again in 41 seconds
[2021-01-04 03:14:21,131] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2021-01-04 03:14:21,132] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2021-01-04 03:14:21,241] Thread for pastebin.com crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2021-01-04 03:14:21,241] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2021-01-04 03:14:22,151] Thread for slexy.org crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2021-01-04 03:14:22,151] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'
