### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'text'

### ISSUE THREAD

**Issue by VA2PE** [CIRCL/pystemon#4]
Something seems broken in the pystemon.py script. When running ./pystemon.py, I get the following:

```
user@ubuntu:~/pystemon$ python2 ./pystemon.py 
./pystemon.py:868: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yamlconfig = yaml.load(open(configfile))
Site: safebin.net is disabled.
Site: slexy.org is enabled, adding to pool...
Site: pastebin.com is enabled, adding to pool...
Site: gist.github.com is disabled.
Site: pastebin.com_pro is disabled.
Site: codepad.org is disabled.
[2020-10-23 09:07:41,143] Using default IP address
[2020-10-23 09:07:41,143] Downloading list of new pastes from slexy.org. Will check again in 20 seconds
[2020-10-23 09:07:41,143] Using default IP address
[2020-10-23 09:07:41,144] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-10-23 09:07:41,144] Downloading list of new pastes from pastebin.com. Will check again in 44 seconds
[2020-10-23 09:07:41,145] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-10-23 09:07:41,145] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2020-10-23 09:07:41,147] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2020-10-23 09:07:41,222] Thread for slexy.org crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-10-23 09:07:41,223] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-10-23 09:07:41,239] Thread for pastebin.com crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-10-23 09:07:41,239] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-10-23 09:08:01,241] Downloading list of new pastes from slexy.org. Will check again in 29 seconds
[2020-10-23 09:08:01,242] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-10-23 09:08:01,242] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-10-23 09:08:01,316] Thread for slexy.org crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-10-23 09:08:01,316] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-10-23 09:08:25,268] Downloading list of new pastes from pastebin.com. Will check again in 41 seconds
[2020-10-23 09:08:25,268] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2020-10-23 09:08:25,268] Downloading url: http://pastebin.com/archive with proxy: None and user-agent: None
[2020-10-23 09:08:25,342] Thread for pastebin.com crashed unexpectectly, recovering...: 'tuple' object has no attribute 'text'
[2020-10-23 09:08:25,342] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 151, in get_last_pasties
    htmlPage = response.text
AttributeError: 'tuple' object has no attribute 'text'

[2020-10-23 09:08:30,346] Downloading list of new pastes from slexy.org. Will check again in 16 seconds
[2020-10-23 09:08:30,346] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-10-23 09:08:30,347] Downloading url: http://slexy.org/recent with proxy: None and user-agent: None
[2020-10-23 09:08:30,399] !!Proxy error on http://slexy.org/recent for proxy None.
[2020-10-23 09:08:30,399] Thread for slexy.org crashed unexpectectly, recovering...: local variable 'response' referenced before assignment
[2020-10-23 09:08:30,400] Traceback (most recent call last):
  File "./pystemon.py", line 131, in run
    last_pasties = self.get_last_pasties()
  File "./pystemon.py", line 150, in get_last_pasties
    response = download_url(self.archive_url)
  File "./pystemon.py", line 736, in download_url
    return response
UnboundLocalError: local variable 'response' referenced before assignment
```

Any idea on how to fix this?

**Comment by lesleyxyz** [comment]
I'm having the same issue. Someone was also talking about it in #3

**Comment by osagit** [comment]
This version of pystemon is too far and old from the original cvandeplas/pystemon version.
A merge from original should be done.
